services:
  nuvie-backend:
    depends_on:
        - postgres
    networks:
      - vini-nuvie
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT-8000}:${BACKEND_PORT-8000}"

    build:
      context: ./nuvie-backend

    platform: linux/amd64 # Patch for M1 Mac

    develop:
      # For hot reloading during development
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: ./nuvie-backend
          target: /app
          ignore:
            - .venv/

        # Rebuild if dependencies change
        - action: rebuild
          path: ./nuvie-backend/uv.lock

  postgres:
    image: postgres:17.5-alpine
    networks:
      - vini-nuvie
    env_file:
      # Environment variables for postgres user and password must be set in the
      # .env file!
      - .env
    ports:
      - "${POSTGRES_PORT-5432}:${POSTGRES_PORT-5432}"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'password'
      SERVICE_MANAGER: 'fsm-postgres'
    volumes:
      - 'nuvie-database:/var/lib/postgresql/data/'


volumes:
  nuvie-database:


networks:
  vini-nuvie:
    name: vini-nuvie
    driver: bridge