[project]
name = "nuvie-ingestor"
version = "0.1.0"
description = "Ingestor for Nuvie's project. Imports medical and patient data from external sources (i.e. Synthea)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
