[project]
name = "nuvie-backend"
version = "0.1.0"
description = "Back-end for Nuvie's project. Exposes an API for handling and managing synthetic data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
]
